//! SeaORM entity over the hub-owned `communities` table, projecting only the
//! two columns [`crate::overlay::code`] needs to map an unguessable overlay
//! code to a community: `id` and `overlay_code`
//! (`alembic/versions/0056_communities_overlay_code.py`).
//!
//! Kept separate from [`super::community`] (`id`/`tenant_id`) on purpose:
//! SeaORM selects exactly the declared columns, so each lookup asks the
//! database for -- and the service's DB role needs `SELECT` on -- only what
//! that lookup uses. Read-only: this service never writes `communities`; the
//! code is generated by the column `DEFAULT` and rotated by hub-api.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "communities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    /// 16 lowercase hex characters (64 random bits); `UNIQUE NOT NULL`.
    pub overlay_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
