# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waddles/hub/internal/v1/identity.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "waddles/hub/internal/v1/identity.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n&waddles/hub/internal/v1/identity.proto\x12\x17waddles.hub.internal.v1"n\n\x1dMintEphemeralPseudonymRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x18\n\x10platform_user_id\x18\x03 \x01(\t\x12\x0e\n\x06handle\x18\x04 \x01(\t"g\n\x1eMintEphemeralPseudonymsRequest\x12\x45\n\x05items\x18\x01 \x03(\x0b\x32\x36.waddles.hub.internal.v1.MintEphemeralPseudonymRequest"A\n\x12\x45phemeralPseudonym\x12\x18\n\x10platform_user_id\x18\x01 \x01(\t\x12\x11\n\tpseudonym\x18\x02 \x01(\t"b\n\x1fMintEphemeralPseudonymsResponse\x12?\n\npseudonyms\x18\x01 \x03(\x0b\x32+.waddles.hub.internal.v1.EphemeralPseudonym">\n\x1aResolveDisplayNamesRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\r\n\x05uuids\x18\x02 \x03(\t"N\n\x13ResolvedDisplayName\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0bis_hub_user\x18\x03 \x01(\x08"t\n\x1bResolveDisplayNamesResponse\x12;\n\x05names\x18\x01 \x03(\x0b\x32,.waddles.hub.internal.v1.ResolvedDisplayName\x12\x18\n\x10unresolved_uuids\x18\x02 \x03(\t2\xa3\x02\n\x0fIdentityService\x12\x8c\x01\n\x17MintEphemeralPseudonyms\x12\x37.waddles.hub.internal.v1.MintEphemeralPseudonymsRequest\x1a\x38.waddles.hub.internal.v1.MintEphemeralPseudonymsResponse\x12\x80\x01\n\x13ResolveDisplayNames\x12\x33.waddles.hub.internal.v1.ResolveDisplayNamesRequest\x1a\x34.waddles.hub.internal.v1.ResolveDisplayNamesResponseBPZNgithub.com/penguintechinc/waddles/gen/go/waddles/hub/internal/v1;hubinternalv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "waddles.hub.internal.v1.identity_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"ZNgithub.com/penguintechinc/waddles/gen/go/waddles/hub/internal/v1;hubinternalv1"
    )
    _globals["_MINTEPHEMERALPSEUDONYMREQUEST"]._serialized_start = 67
    _globals["_MINTEPHEMERALPSEUDONYMREQUEST"]._serialized_end = 177
    _globals["_MINTEPHEMERALPSEUDONYMSREQUEST"]._serialized_start = 179
    _globals["_MINTEPHEMERALPSEUDONYMSREQUEST"]._serialized_end = 282
    _globals["_EPHEMERALPSEUDONYM"]._serialized_start = 284
    _globals["_EPHEMERALPSEUDONYM"]._serialized_end = 349
    _globals["_MINTEPHEMERALPSEUDONYMSRESPONSE"]._serialized_start = 351
    _globals["_MINTEPHEMERALPSEUDONYMSRESPONSE"]._serialized_end = 449
    _globals["_RESOLVEDISPLAYNAMESREQUEST"]._serialized_start = 451
    _globals["_RESOLVEDISPLAYNAMESREQUEST"]._serialized_end = 513
    _globals["_RESOLVEDDISPLAYNAME"]._serialized_start = 515
    _globals["_RESOLVEDDISPLAYNAME"]._serialized_end = 593
    _globals["_RESOLVEDISPLAYNAMESRESPONSE"]._serialized_start = 595
    _globals["_RESOLVEDISPLAYNAMESRESPONSE"]._serialized_end = 711
    _globals["_IDENTITYSERVICE"]._serialized_start = 714
    _globals["_IDENTITYSERVICE"]._serialized_end = 1005
# @@protoc_insertion_point(module_scope)
