# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from waddles.hub.internal.v1 import (
    identity_pb2 as waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2,
)

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in waddles/hub/internal/v1/identity_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class IdentityServiceStub:
    """Mints and resolves ephemeral, per-tenant pseudonyms so svc-ingest/
    svc-process/svc-action never handle raw platform identifiers or hub
    user PII directly (security.md PII Tokenization: "the API server is
    the PII boundary").
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MintEphemeralPseudonyms = channel.unary_unary(
            "/waddles.hub.internal.v1.IdentityService/MintEphemeralPseudonyms",
            request_serializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.MintEphemeralPseudonymsRequest.SerializeToString,
            response_deserializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.MintEphemeralPseudonymsResponse.FromString,
            _registered_method=True,
        )
        self.ResolveDisplayNames = channel.unary_unary(
            "/waddles.hub.internal.v1.IdentityService/ResolveDisplayNames",
            request_serializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveDisplayNamesRequest.SerializeToString,
            response_deserializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveDisplayNamesResponse.FromString,
            _registered_method=True,
        )
        self.ResolveHandle = channel.unary_unary(
            "/waddles.hub.internal.v1.IdentityService/ResolveHandle",
            request_serializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveHandleRequest.SerializeToString,
            response_deserializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveHandleResponse.FromString,
            _registered_method=True,
        )


class IdentityServiceServicer:
    """Mints and resolves ephemeral, per-tenant pseudonyms so svc-ingest/
    svc-process/svc-action never handle raw platform identifiers or hub
    user PII directly (security.md PII Tokenization: "the API server is
    the PII boundary").
    """

    def MintEphemeralPseudonyms(self, request, context):
        """Batch-mints (or returns the existing) ephemeral pseudonym for each
        (tenant_id, platform, platform_user_id) tuple. Required scope:
        "identity:ephemeral:mint".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResolveDisplayNames(self, request, context):
        """Resolves up to 100 UUIDs (hub_users.uuid OR ephemeral pseudonyms) to
        display names in one call, so callers batch instead of N+1. Required
        scope: "identity:displayname:read".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResolveHandle(self, request, context):
        """Resolves ONE raw user reference as a chat user typed it -- a platform
        handle ("@bob", "bob") or a Discord mention ("<@123>", "<@!123>") -- to
        the stable UUID of that identity, entirely inside the hub-api PII
        boundary: the raw handle is matched here and never stored, echoed or
        logged; only the UUID comes back. NOT_FOUND = no such identity in the
        tenant (or tenant unknown), FAILED_PRECONDITION = the handle matches
        more than one identity (never guessed), INVALID_ARGUMENT = malformed
        or non-user reference (role/channel mention, @everyone). Required
        scope: "identity:handle:resolve".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "MintEphemeralPseudonyms": grpc.unary_unary_rpc_method_handler(
            servicer.MintEphemeralPseudonyms,
            request_deserializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.MintEphemeralPseudonymsRequest.FromString,
            response_serializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.MintEphemeralPseudonymsResponse.SerializeToString,
        ),
        "ResolveDisplayNames": grpc.unary_unary_rpc_method_handler(
            servicer.ResolveDisplayNames,
            request_deserializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveDisplayNamesRequest.FromString,
            response_serializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveDisplayNamesResponse.SerializeToString,
        ),
        "ResolveHandle": grpc.unary_unary_rpc_method_handler(
            servicer.ResolveHandle,
            request_deserializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveHandleRequest.FromString,
            response_serializer=waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveHandleResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "waddles.hub.internal.v1.IdentityService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "waddles.hub.internal.v1.IdentityService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class IdentityService:
    """Mints and resolves ephemeral, per-tenant pseudonyms so svc-ingest/
    svc-process/svc-action never handle raw platform identifiers or hub
    user PII directly (security.md PII Tokenization: "the API server is
    the PII boundary").
    """

    @staticmethod
    def MintEphemeralPseudonyms(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/waddles.hub.internal.v1.IdentityService/MintEphemeralPseudonyms",
            waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.MintEphemeralPseudonymsRequest.SerializeToString,
            waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.MintEphemeralPseudonymsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResolveDisplayNames(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/waddles.hub.internal.v1.IdentityService/ResolveDisplayNames",
            waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveDisplayNamesRequest.SerializeToString,
            waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveDisplayNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResolveHandle(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/waddles.hub.internal.v1.IdentityService/ResolveHandle",
            waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveHandleRequest.SerializeToString,
            waddles_dot_hub_dot_internal_dot_v1_dot_identity__pb2.ResolveHandleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
