# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waddles/hub/internal/v1/key.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "waddles/hub/internal/v1/key.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!waddles/hub/internal/v1/key.proto\x12\x17waddles.hub.internal.v1"o\n\x13GetStreamDekRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07purpose\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\x12#\n\x1b\x63\x61ller_ephemeral_public_key\x18\x04 \x01(\x0c"P\n\x14GetStreamDekResponse\x12\x12\n\nsealed_dek\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\r2y\n\nKeyService\x12k\n\x0cGetStreamDek\x12,.waddles.hub.internal.v1.GetStreamDekRequest\x1a-.waddles.hub.internal.v1.GetStreamDekResponseBPZNgithub.com/penguintechinc/waddles/gen/go/waddles/hub/internal/v1;hubinternalv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "waddles.hub.internal.v1.key_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"ZNgithub.com/penguintechinc/waddles/gen/go/waddles/hub/internal/v1;hubinternalv1"
    )
    _globals["_GETSTREAMDEKREQUEST"]._serialized_start = 62
    _globals["_GETSTREAMDEKREQUEST"]._serialized_end = 173
    _globals["_GETSTREAMDEKRESPONSE"]._serialized_start = 175
    _globals["_GETSTREAMDEKRESPONSE"]._serialized_end = 255
    _globals["_KEYSERVICE"]._serialized_start = 257
    _globals["_KEYSERVICE"]._serialized_end = 378
# @@protoc_insertion_point(module_scope)
