"""Build-time-only script -- never imported by a bundle or by the SDK itself at runtime.

Run BEFORE ``componentize-py componentize`` (host-side, ordinary CPython,
never inside the sandbox) to force componentize-py's static
dependency-closure discovery to see every module physically present under a
bundle's ``bundles/`` package, regardless of whether the bundle code imports
them lazily, dynamically, or not at all this run (spike round 2, blocker 2).

Adapted from ``spikes/penguin-dal-wasm/scripts/generate_bundle_preimports.py``
(branch ``spike/penguin-dal-wasm``, commit ``964f2729``). The compiler's
Python build recipe is expected to invoke the equivalent logic inline rather
than shelling out to this script directly -- this script is kept here, as a
standalone entry point, for bundle authors who want to run it locally during
development, matching the compiler's own logic byte-for-byte (kept in
lockstep by convention -- if one changes, update the other).
"""

from __future__ import annotations

import pkgutil
import sys
from pathlib import Path


def discover_bundle_modules(bundle_root: Path) -> list[str]:
    """Return every importable module name under ``bundle_root/bundles/``."""
    sys.path.insert(0, str(bundle_root))
    import bundles  # the package physically present in the bundle's source tree

    return sorted(m.name for m in pkgutil.walk_packages(bundles.__path__, prefix="bundles."))


def main() -> None:
    """Write ``_bundle_preimports.py`` for the bundle root given on argv[1]."""
    if len(sys.argv) != 2:
        print("usage: generate_bundle_preimports.py <bundle_root>", file=sys.stderr)
        raise SystemExit(2)
    bundle_root = Path(sys.argv[1])
    modules = discover_bundle_modules(bundle_root)
    out_path = bundle_root / "_bundle_preimports.py"
    lines = [
        '"""AUTO-GENERATED by generate_bundle_preimports.py -- DO NOT EDIT."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    lines += [f"import {name}  # noqa: F401" for name in modules]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} with {len(modules)} pre-import(s): {modules}")


if __name__ == "__main__":
    main()
