// `wit-bindgen c-sharp` requires this EXACT type name
// (`ProcessStageExportsImpl`) implementing `IProcessStageExports` in this
// EXACT namespace -- both dictated by the generated
// `StageWorld.wit.Exports.waddle.bundle.v1_0_0.ProcessStageExportsInterop`
// (`generated/wit/`, gitignored, regenerated by `dotnet build`), whose
// `wasmExportTransform` thunk calls `ProcessStageExportsImpl.Transform`
// unconditionally; the class does not need to be referenced anywhere else
// for `wit-bindgen`'s generated interop to find it (discovered empirically
// building this bundle before it was ported onto `waddle-sdk-cs` -- see git
// history for the original hand-rolled version of this file).
//
// Deliberately thin: converts the wit-bindgen-generated `Types.PlatformEvent`
// to/from `WaddleSdk.Types.PlatformEventInfo` and delegates all real logic to
// `CspingLogic` (`waddle-sdk-cs`'s `WaddleProcessStage` base class) -- see
// `sdk/waddle-sdk-cs/README.md` "Writing a bundle" and
// `bundles/csharp/superpenguin-roll/ProcessStageExportsImpl.cs` for the
// identical shape every C# bundle on the SDK uses.
namespace StageWorld.wit.Exports.waddle.bundle.v1_0_0;

using WaddleBundleCsping;
using WaddleSdk.Types;
using Types = global::StageWorld.wit.Imports.waddle.bundle.v1_0_0.ITypesImports;

public class ProcessStageExportsImpl : IProcessStageExports
{
    private static readonly CspingLogic Logic = new();
    private static readonly WaddleHostAdapter Host = new();

    public static Types.PlatformEvent? Transform(Types.PlatformEvent @event)
    {
        var sdkEvent = new PlatformEventInfo(@event.platform, @event.eventType, @event.actor, @event.payloadJson, @event.occurredAt);

        var result = Logic.Run(sdkEvent, Host);
        if (result is null)
        {
            return null;
        }

        return new Types.PlatformEvent(result.Platform, result.EventType, result.Actor, result.PayloadJson, result.OccurredAt);
    }
}
