// Minimal, real `!csping` -> `pong (c#)` chat bundle: the C#-SDK-toolchain
// spike's process-stage half, C# equivalent of `bundles/rust/ping/src/lib.rs`
// and `bundles/python/pyping/src/app.py`.
//
// `wit-bindgen c-sharp` requires this EXACT type name
// (`ProcessStageExportsImpl`) implementing `IProcessStageExports` in this
// EXACT namespace -- both dictated by the generated
// `StageWorld.wit.Exports.waddle.bundle.v1_0_0.ProcessStageExportsInterop`
// (`generated/wit/`, gitignored, regenerated by `dotnet build`), whose
// `wasmExportTransform` thunk calls `ProcessStageExportsImpl.Transform`
// unconditionally; the class does not need to be referenced anywhere else
// for `wit-bindgen`'s generated interop to find it (confirmed empirically:
// omitting it entirely fails the build with
// `CS0103: The name 'ProcessStageExportsImpl' does not exist in the
// current context`, which is how this exact shape was discovered rather
// than guessed).
//
// `result<option<platform-event>, unsupported-stage>` (this bundle never
// needed `--with-wit-results`) lowers to a C# signature that returns the
// inner `option` as `PlatformEvent?` directly and represents `Err` as a
// thrown `WitException<T>` -- this bundle never throws (it always matches
// or drops silently), so `IProcessStageExports.Transform`'s implicit
// `unsupported-stage` path is unused here, mirroring `bundles/rust/ping`
// (which also never returns `Err`).
namespace StageWorld.wit.Exports.waddle.bundle.v1_0_0;

using System.Text.Json;
using System.Text.Json.Nodes;
using Types = global::StageWorld.wit.Imports.waddle.bundle.v1_0_0.ITypesImports;

/// <summary>
/// Implements `process-stage.transform`: recognizes the exact command
/// `!csping` in an inbound `chat.message`'s JSON `payload-json` and
/// rewrites the event into a `pong (c#)` reply on the same platform/
/// channel. Non-matching or non-object payloads produce no reply (`null`)
/// rather than throwing -- this bundle must never fail the pipeline over
/// an event it was never meant to react to, same contract as the Rust and
/// Python siblings.
/// </summary>
public class ProcessStageExportsImpl : IProcessStageExports
{
    /// <summary>The exact command text this bundle reacts to, matched against the trimmed `text` field only.</summary>
    private const string PingCommand = "!csping";

    /// <summary>The reply body sent back for a matching command.</summary>
    private const string PongReply = "pong (c#)";

    public static Types.PlatformEvent? Transform(Types.PlatformEvent @event)
    {
        JsonNode? node;
        try
        {
            node = JsonNode.Parse(@event.payloadJson);
        }
        catch (JsonException)
        {
            // Not valid JSON at all: not our command, drop silently.
            return null;
        }

        if (node is not JsonObject obj)
        {
            return null;
        }

        if (obj["text"] is not JsonValue textValue || !textValue.TryGetValue(out string? text))
        {
            return null;
        }

        if (text.Trim() != PingCommand)
        {
            return null;
        }

        var reply = new JsonObject
        {
            ["text"] = PongReply,
            ["channel_id"] = obj["channel_id"]?.DeepClone(),
        };

        return new Types.PlatformEvent(
            @event.platform,
            @event.eventType,
            @event.actor,
            reply.ToJsonString(),
            @event.occurredAt);
    }
}
