/**
 * Request-contract tests for `adminApi`: every helper is called against a recording HTTP adapter and must emit the exact method/URL/params/body hub-api expects.
 */
import { afterAll, describe, it } from 'vitest';

import api, { adminApi } from '../api';
import { assertContractRow, recordRequests, type ContractRow } from '../../test/apiContract';

const rec = recordRequests(api);
afterAll(rec.restore);

const ADMINAPI_ROWS: readonly ContractRow[] = [
  ['getSettings(communityId)', 'GET /api/v1/admin/{communityId}/settings'],
  ['updateSettings(communityId, data)', 'PUT /api/v1/admin/{communityId}/settings', { body: '@data' }],
  ['getJoinRequests(communityId, params)', 'GET /api/v1/admin/{communityId}/join-requests'],
  ['approveJoinRequest(communityId, requestId, note)', 'POST /api/v1/admin/{communityId}/join-requests/{requestId}/approve', { body: { note: '@note' } }],
  ['rejectJoinRequest(communityId, requestId, note)', 'POST /api/v1/admin/{communityId}/join-requests/{requestId}/reject', { body: { note: '@note' } }],
  ['getMembers(communityId, params)', 'GET /api/v1/admin/{communityId}/members'],
  ['updateMemberRole(communityId, userId, role)', 'PUT /api/v1/admin/{communityId}/members/{userId}/role', { body: { role: '@role' } }],
  ['adjustReputation(communityId, userId, amount, reason)', 'PUT /api/v1/admin/{communityId}/members/{userId}/reputation', { body: { amount: '@amount', reason: '@reason' } }],
  ['removeMember(communityId, userId, reason)', 'DELETE /api/v1/admin/{communityId}/members/{userId}', { body: { reason: '@reason' } }],
  ['getModules(communityId)', 'GET /api/v1/admin/{communityId}/modules'],
  ['updateModuleConfig(communityId, moduleId, data)', 'PUT /api/v1/admin/{communityId}/modules/{moduleId}/config', { body: '@data' }],
  ['getConnectedPlatforms(communityId)', 'GET /api/v1/admin/{communityId}/connected-platforms'],
  ['getCommunityOAuthCredentials(communityId)', 'GET /api/v1/admin/{communityId}/oauth/credentials'],
  ['createCommunityOAuthCredential(communityId, data)', 'POST /api/v1/admin/{communityId}/oauth/credentials', { body: '@data' }],
  ['updateCommunityOAuthCredential(communityId, id, data)', 'PUT /api/v1/admin/{communityId}/oauth/credentials/{id}', { body: '@data' }],
  ['deleteCommunityOAuthCredential(communityId, id)', 'DELETE /api/v1/admin/{communityId}/oauth/credentials/{id}'],
  ['testCommunityOAuthCredential(communityId, id)', 'POST /api/v1/admin/{communityId}/oauth/credentials/{id}/test'],
  ['getBrowserSources(communityId)', 'GET /api/v1/admin/{communityId}/browser-sources'],
  ['regenerateBrowserSources(communityId, sourceType)', 'POST /api/v1/admin/{communityId}/browser-sources/regenerate', { body: { sourceType: '@sourceType' } }],
  ['getDomains(communityId)', 'GET /api/v1/admin/{communityId}/domains'],
  ['addDomain(communityId, domain)', 'POST /api/v1/admin/{communityId}/domains', { body: { domain: '@domain' } }],
  ['verifyDomain(communityId, domainId)', 'POST /api/v1/admin/{communityId}/domains/{domainId}/verify'],
  ['removeDomain(communityId, domainId)', 'DELETE /api/v1/admin/{communityId}/domains/{domainId}'],
  ['generateTempPassword(communityId, data)', 'POST /api/v1/admin/{communityId}/temp-password', { body: '@data' }],
  ['getServers(communityId, params)', 'GET /api/v1/admin/{communityId}/servers'],
  ['updateServer(communityId, serverId, data)', 'PUT /api/v1/admin/{communityId}/servers/{serverId}', { body: '@data' }],
  ['removeServer(communityId, serverId)', 'DELETE /api/v1/admin/{communityId}/servers/{serverId}'],
  ['getServerLinkRequests(communityId, params)', 'GET /api/v1/admin/{communityId}/server-link-requests'],
  ['approveServerLinkRequest(communityId, requestId, note)', 'POST /api/v1/admin/{communityId}/server-link-requests/{requestId}/approve', { body: { note: '@note' } }],
  ['rejectServerLinkRequest(communityId, requestId, note)', 'POST /api/v1/admin/{communityId}/server-link-requests/{requestId}/reject', { body: { note: '@note' } }],
  ['getMirrorGroups(communityId)', 'GET /api/v1/admin/{communityId}/mirror-groups'],
  ['getMirrorGroup(communityId, groupId)', 'GET /api/v1/admin/{communityId}/mirror-groups/{groupId}'],
  ['createMirrorGroup(communityId, data)', 'POST /api/v1/admin/{communityId}/mirror-groups', { body: '@data' }],
  ['updateMirrorGroup(communityId, groupId, data)', 'PUT /api/v1/admin/{communityId}/mirror-groups/{groupId}', { body: '@data' }],
  ['deleteMirrorGroup(communityId, groupId)', 'DELETE /api/v1/admin/{communityId}/mirror-groups/{groupId}'],
  ['addMirrorGroupMember(communityId, groupId, data)', 'POST /api/v1/admin/{communityId}/mirror-groups/{groupId}/members', { body: '@data' }],
  ['updateMirrorGroupMember(communityId, groupId, memberId, data)', 'PUT /api/v1/admin/{communityId}/mirror-groups/{groupId}/members/{memberId}', { body: '@data' }],
  ['removeMirrorGroupMember(communityId, groupId, memberId)', 'DELETE /api/v1/admin/{communityId}/mirror-groups/{groupId}/members/{memberId}'],
  ['getLeaderboardConfig(communityId)', 'GET /api/v1/admin/{communityId}/leaderboard-config'],
  ['updateLeaderboardConfig(communityId, data)', 'PUT /api/v1/admin/{communityId}/leaderboard-config', { body: '@data' }],
  ['updateCommunityProfile(communityId, data)', 'PUT /api/v1/admin/{communityId}/profile', { body: '@data' }],
  ['deleteCommunityLogo(communityId)', 'DELETE /api/v1/admin/{communityId}/logo'],
  ['deleteCommunityBanner(communityId)', 'DELETE /api/v1/admin/{communityId}/banner'],
  ['getReputationConfig(communityId)', 'GET /api/v1/admin/{communityId}/reputation/config'],
  ['updateReputationConfig(communityId, data)', 'PUT /api/v1/admin/{communityId}/reputation/config', { body: '@data' }],
  ['getAtRiskUsers(communityId, params)', 'GET /api/v1/admin/{communityId}/reputation/at-risk'],
  ['getReputationLeaderboard(communityId, params)', 'GET /api/v1/admin/{communityId}/reputation/leaderboard'],
  ['getAIInsights(communityId, params)', 'GET /api/v1/admin/{communityId}/ai-insights'],
  ['getAIInsight(communityId, insightId)', 'GET /api/v1/admin/{communityId}/ai-insights/{insightId}'],
  ['getAIResearcherConfig(communityId)', 'GET /api/v1/admin/{communityId}/ai-researcher/config'],
  ['updateAIResearcherConfig(communityId, data)', 'PUT /api/v1/admin/{communityId}/ai-researcher/config', { body: '@data' }],
  ['getAvailableAIModels(communityId)', 'GET /api/v1/admin/{communityId}/ai-researcher/available-models'],
  ['getAIChatterConfig(communityId)', 'GET /api/v1/admin/{communityId}/ai-chatter/config'],
  ['updateAIChatterConfig(communityId, config)', 'PUT /api/v1/admin/{communityId}/ai-chatter/config', { body: '@config' }],
  ['getBotDetections(communityId, params)', 'GET /api/v1/admin/{communityId}/bot-detection'],
  ['getBotDetectionResults(communityId, params)', 'GET /api/v1/admin/{communityId}/bot-detection'],
  ['getBotScore(communityId)', 'GET /api/v1/admin/{communityId}/bot-score'],
  ['getSuspectedBots(communityId, params)', 'GET /api/v1/admin/{communityId}/suspected-bots'],
  ['reviewSuspectedBot(communityId, botId, data)', 'PUT /api/v1/admin/{communityId}/suspected-bots/{botId}/review', { body: '@data' }],
  ['reviewBotDetection(communityId, resultId, data)', 'POST /api/v1/admin/{communityId}/bot-detection/{resultId}/review', { body: '@data' }],
  ['markBotDetectionReviewed(communityId, resultId)', 'POST /api/v1/admin/{communityId}/bot-detection/{resultId}/mark-reviewed'],
  ['getAIContext(communityId)', 'GET /api/v1/admin/{communityId}/ai-context'],
  ['getLoyaltyConfig(communityId)', 'GET /api/v1/admin/{communityId}/loyalty/config'],
  ['updateLoyaltyConfig(communityId, data)', 'PUT /api/v1/admin/{communityId}/loyalty/config', { body: '@data' }],
  ['getLoyaltyLeaderboard(communityId, params)', 'GET /api/v1/admin/{communityId}/loyalty/leaderboard'],
  ['adjustLoyaltyBalance(communityId, userId, data)', 'PUT /api/v1/admin/{communityId}/loyalty/user/{userId}/balance', { body: '@data' }],
  ['wipeLoyaltyCurrency(communityId)', 'POST /api/v1/admin/{communityId}/loyalty/wipe'],
  ['getLoyaltyStats(communityId)', 'GET /api/v1/admin/{communityId}/loyalty/stats'],
  ['getAnnouncements(communityId, params)', 'GET /api/v1/admin/{communityId}/announcements'],
  ['getAnnouncement(communityId, announcementId)', 'GET /api/v1/admin/{communityId}/announcements/{announcementId}'],
  ['createAnnouncement(communityId, data)', 'POST /api/v1/admin/{communityId}/announcements', { body: '@data' }],
  ['updateAnnouncement(communityId, announcementId, data)', 'PUT /api/v1/admin/{communityId}/announcements/{announcementId}', { body: '@data' }],
  ['deleteAnnouncement(communityId, announcementId)', 'DELETE /api/v1/admin/{communityId}/announcements/{announcementId}'],
  ['publishAnnouncement(communityId, announcementId)', 'POST /api/v1/admin/{communityId}/announcements/{announcementId}/publish'],
  ['pinAnnouncement(communityId, announcementId)', 'PUT /api/v1/admin/{communityId}/announcements/{announcementId}/pin'],
  ['unpinAnnouncement(communityId, announcementId)', 'PUT /api/v1/admin/{communityId}/announcements/{announcementId}/unpin'],
  ['archiveAnnouncement(communityId, announcementId)', 'POST /api/v1/admin/{communityId}/announcements/{announcementId}/archive'],
  ['broadcastAnnouncement(communityId, announcementId, platforms)', 'POST /api/v1/admin/{communityId}/announcements/{announcementId}/broadcast', { body: { platforms: '@platforms' } }],
  ['getBroadcastStatus(communityId, announcementId)', 'GET /api/v1/admin/{communityId}/announcements/{announcementId}/broadcast-status'],
  ['getAnalyticsBasic(communityId)', 'GET /api/v1/admin/{communityId}/analytics/basic'],
  ['getAnalyticsPoll(communityId)', 'GET /api/v1/admin/{communityId}/analytics/poll'],
  ['getAnalyticsHealthScore(communityId)', 'GET /api/v1/admin/{communityId}/analytics/health-score'],
  ['getAnalyticsBadActors(communityId, params)', 'GET /api/v1/admin/{communityId}/analytics/bad-actors'],
  ['getAnalyticsRetention(communityId)', 'GET /api/v1/admin/{communityId}/analytics/retention'],
  ['getSecurityConfig(communityId)', 'GET /api/v1/admin/{communityId}/security/config'],
  ['updateSecurityConfig(communityId, data)', 'PUT /api/v1/admin/{communityId}/security/config', { body: '@data' }],
  ['getSecurityBlockedWords(communityId, params)', 'GET /api/v1/admin/{communityId}/security/blocked-words'],
  ['addSecurityBlockedWord(communityId, data)', 'POST /api/v1/admin/{communityId}/security/blocked-words', { body: '@data' }],
  ['updateSecurityBlockedWord(communityId, wordId, data)', 'PUT /api/v1/admin/{communityId}/security/blocked-words/{wordId}', { body: '@data' }],
  ['deleteSecurityBlockedWord(communityId, wordId)', 'DELETE /api/v1/admin/{communityId}/security/blocked-words/{wordId}'],
  ['getSecurityWarnings(communityId, params)', 'GET /api/v1/admin/{communityId}/security/warnings'],
  ['getSecurityModerationLog(communityId, params)', 'GET /api/v1/admin/{communityId}/security/moderation-log'],
  ['getShoutoutConfig(communityId)', 'GET /api/v1/admin/{communityId}/shoutout/config'],
  ['updateShoutoutConfig(communityId, data)', 'PUT /api/v1/admin/{communityId}/shoutout/config', { body: '@data' }],
  ['getShoutoutCreators(communityId)', 'GET /api/v1/admin/{communityId}/shoutout/creators'],
  ['addShoutoutCreator(communityId, data)', 'POST /api/v1/admin/{communityId}/shoutout/creators', { body: '@data' }],
  ['removeShoutoutCreator(communityId, creatorId)', 'DELETE /api/v1/admin/{communityId}/shoutout/creators/{creatorId}'],
  ['getShoutoutHistory(communityId, params)', 'GET /api/v1/admin/{communityId}/shoutout/history'],
  ['getTranslationConfig(communityId)', 'GET /api/v1/admin/{communityId}/translation/config'],
  ['updateTranslationConfig(communityId, config)', 'PUT /api/v1/admin/{communityId}/translation/config', { body: '@config' }],
  ['getMusicSettings(communityId)', 'GET /api/v1/admin/{communityId}/music/settings'],
  ['updateMusicSettings(communityId, settings)', 'PUT /api/v1/admin/{communityId}/music/settings', { body: '@settings' }],
  ['getMusicProviders(communityId)', 'GET /api/v1/admin/{communityId}/music/providers'],
  ['initiateMusicProviderOAuth(communityId, provider)', 'POST /api/v1/admin/{communityId}/music/providers/{provider}/oauth'],
  ['disconnectMusicProvider(communityId, provider)', 'DELETE /api/v1/admin/{communityId}/music/providers/{provider}'],
  ['updateMusicProviderConfig(communityId, provider, config)', 'PUT /api/v1/admin/{communityId}/music/providers/{provider}/config', { body: '@config' }],
  ['getRadioStations(communityId)', 'GET /api/v1/admin/{communityId}/music/radio-stations'],
  ['addRadioStation(communityId, station)', 'POST /api/v1/admin/{communityId}/music/radio-stations', { body: '@station' }],
  ['deleteRadioStation(communityId, stationId)', 'DELETE /api/v1/admin/{communityId}/music/radio-stations/{stationId}'],
  ['testRadioStreamUrl(communityId, stationId)', 'POST /api/v1/admin/{communityId}/music/radio-stations/{stationId}/test'],
  ['setDefaultRadioStation(communityId, stationId)', 'PUT /api/v1/admin/{communityId}/music/radio-stations/{stationId}/default'],
  ['getMusicDashboard(communityId)', 'GET /api/v1/admin/{communityId}/music/dashboard'],
  ['controlPlayback(communityId, action)', 'POST /api/v1/admin/{communityId}/music/playback/control', { body: { action: '@action' } }],
  ['removeMusicQueueItem(communityId, itemId)', 'DELETE /api/v1/admin/{communityId}/music-station/queue/{itemId}'],
  ['getMusicStationPolicy(communityId)', 'GET /api/v1/admin/{communityId}/music-station/policy'],
  ['updateMusicStationPolicy(communityId, policy)', 'PUT /api/v1/admin/{communityId}/music-station/policy', { body: '@policy' }],
  ['getCalendarEvents(communityId, params)', 'GET /api/v1/admin/{communityId}/calendar/events'],
  ['createCalendarEvent(communityId, data)', 'POST /api/v1/admin/{communityId}/calendar/events', { body: '@data' }],
  ['getCalendarEvent(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}'],
  ['updateCalendarEvent(communityId, eventId, data)', 'PUT /api/v1/admin/{communityId}/calendar/events/{eventId}', { body: '@data' }],
  ['deleteCalendarEvent(communityId, eventId)', 'DELETE /api/v1/admin/{communityId}/calendar/events/{eventId}'],
  ['approveCalendarEvent(communityId, eventId)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/approve'],
  ['rejectCalendarEvent(communityId, eventId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/reject', { body: '@data' }],
  ['getEventRsvpCounts(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/rsvp-counts'],
  ['getEventAttendees(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/attendees'],
  ['getTicketTypes(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/ticket-types'],
  ['createTicketType(communityId, eventId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/ticket-types', { body: '@data' }],
  ['updateTicketType(communityId, eventId, typeId, data)', 'PUT /api/v1/admin/{communityId}/calendar/events/{eventId}/ticket-types/{typeId}', { body: '@data' }],
  ['deleteTicketType(communityId, eventId, typeId)', 'DELETE /api/v1/admin/{communityId}/calendar/events/{eventId}/ticket-types/{typeId}'],
  ['getTickets(communityId, eventId, params)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/tickets'],
  ['createTicket(communityId, eventId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/tickets', { body: '@data' }],
  ['getTicket(communityId, eventId, ticketId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/tickets/{ticketId}'],
  ['cancelTicket(communityId, eventId, ticketId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/tickets/{ticketId}/cancel', { body: '@data' }],
  ['transferTicket(communityId, eventId, ticketId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/tickets/{ticketId}/transfer', { body: '@data' }],
  ['verifyTicket(ticketCode)', 'POST /api/v1/admin/calendar/verify-ticket', { body: { ticket_code: '@ticketCode', perform_checkin: true } }],
  ['checkIn(communityId, eventId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/check-in', { body: '@data' }],
  ['undoCheckIn(communityId, eventId, ticketId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/tickets/{ticketId}/undo-check-in', { body: '@data' }],
  ['getAttendanceStats(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/attendance'],
  ['getCheckInLog(communityId, eventId, params)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/check-in-log'],
  ['exportAttendance(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/attendance/export', { params: { format: 'json' } }],
  ['getEventAdmins(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/admins'],
  ['assignEventAdmin(communityId, eventId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/admins', { body: '@data' }],
  ['updateEventAdmin(communityId, eventId, adminId, data)', 'PUT /api/v1/admin/{communityId}/calendar/events/{eventId}/admins/{adminId}', { body: '@data' }],
  ['revokeEventAdmin(communityId, eventId, adminId, data)', 'DELETE /api/v1/admin/{communityId}/calendar/events/{eventId}/admins/{adminId}', { body: '@data' }],
  ['getMyEventPermissions(communityId, eventId)', 'GET /api/v1/admin/{communityId}/calendar/events/{eventId}/my-permissions'],
  ['enableTicketing(communityId, eventId, data)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/ticketing/enable', { body: '@data' }],
  ['disableTicketing(communityId, eventId)', 'POST /api/v1/admin/{communityId}/calendar/events/{eventId}/ticketing/disable'],
  ['getStreamConfig(communityId)', 'GET /api/v1/admin/{communityId}/streams'],
  ['createStreamConfig(communityId)', 'POST /api/v1/admin/{communityId}/streams'],
  ['regenerateStreamKey(communityId)', 'POST /api/v1/admin/{communityId}/streams/key/regenerate'],
  ['getStreamDestinations(communityId)', 'GET /api/v1/admin/{communityId}/streams/destinations'],
  ['addStreamDestination(communityId, data)', 'POST /api/v1/admin/{communityId}/streams/destinations', { body: '@data' }],
  ['removeStreamDestination(communityId, destId)', 'DELETE /api/v1/admin/{communityId}/streams/destinations/{destId}'],
  ['toggleStreamForceCut(communityId, destId)', 'PUT /api/v1/admin/{communityId}/streams/destinations/{destId}/force-cut'],
  ['getStreamStatus(communityId)', 'GET /api/v1/admin/{communityId}/streams/status'],
  ['getCallRooms(communityId)', 'GET /api/v1/admin/{communityId}/calls/rooms'],
  ['getCallRoom(communityId, roomName)', 'GET /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}'],
  ['createCallRoom(communityId, data)', 'POST /api/v1/admin/{communityId}/calls/rooms', { body: '@data' }],
  ['deleteCallRoom(communityId, roomName)', 'DELETE /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}'],
  ['lockCallRoom(communityId, roomName)', 'POST /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/lock'],
  ['unlockCallRoom(communityId, roomName)', 'POST /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/unlock'],
  ['getCallParticipants(communityId, roomName)', 'GET /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/participants'],
  ['kickCallParticipant(communityId, roomName, identity)', 'POST /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/kick', { body: { identity: '@identity' } }],
  ['muteAllCallParticipants(communityId, roomName)', 'POST /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/mute-all'],
  ['getRaisedHands(communityId, roomName)', 'GET /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/raised-hands'],
  ['acknowledgeHand(communityId, roomName, userId)', 'POST /api/v1/admin/{communityId}/calls/rooms/{roomName|enc}/acknowledge-hand', { body: { user_id: '@userId' } }],
  ['getPolls(communityId)', 'GET /api/v1/admin/{communityId}/polls'],
  ['getPoll(communityId, pollId)', 'GET /api/v1/admin/{communityId}/polls/{pollId}'],
  ['createPoll(communityId, data)', 'POST /api/v1/admin/{communityId}/polls', { body: '@data' }],
  ['deletePoll(communityId, pollId)', 'DELETE /api/v1/admin/{communityId}/polls/{pollId}'],
  ['getForms(communityId)', 'GET /api/v1/admin/{communityId}/forms'],
  ['getForm(communityId, formId)', 'GET /api/v1/admin/{communityId}/forms/{formId}'],
  ['createForm(communityId, data)', 'POST /api/v1/admin/{communityId}/forms', { body: '@data' }],
  ['deleteForm(communityId, formId)', 'DELETE /api/v1/admin/{communityId}/forms/{formId}'],
  ['getFormSubmissions(communityId, formId)', 'GET /api/v1/admin/{communityId}/forms/{formId}/submissions'],
  ['getSupportCategories(communityId)', 'GET /api/v1/admin/{communityId}/support/categories'],
  ['createSupportCategory(communityId, data)', 'POST /api/v1/admin/{communityId}/support/categories', { body: '@data' }],
  ['updateSupportCategory(communityId, categoryId, data)', 'PUT /api/v1/admin/{communityId}/support/categories/{categoryId}', { body: '@data' }],
  ['deleteSupportCategory(communityId, categoryId)', 'DELETE /api/v1/admin/{communityId}/support/categories/{categoryId}'],
  ['getSupportTickets(communityId, params)', 'GET /api/v1/admin/{communityId}/support/tickets'],
  ['getSupportTicket(communityId, ticketId)', 'GET /api/v1/admin/{communityId}/support/tickets/{ticketId}'],
  ['updateTicketStatus(communityId, ticketId, status)', 'PUT /api/v1/admin/{communityId}/support/tickets/{ticketId}/status', { body: { status: '@status' } }],
  ['assignSupportTicket(communityId, ticketId, assigneeUserId)', 'PUT /api/v1/admin/{communityId}/support/tickets/{ticketId}/assign', { body: { assignee_user_id: '@assigneeUserId' } }],
  ['updateSupportTicketPriority(communityId, ticketId, priority)', 'PUT /api/v1/admin/{communityId}/support/tickets/{ticketId}/priority', { body: { priority: '@priority' } }],
  ['addSupportTicketComment(communityId, ticketId, content, isInternal)', 'POST /api/v1/admin/{communityId}/support/tickets/{ticketId}/comments', { body: { content: '@content', is_internal: '@isInternal' } }],
  ['getSupportStats(communityId)', 'GET /api/v1/admin/{communityId}/support/stats'],
  ['getCommands(communityId)', 'GET /api/v1/admin/{communityId}/commands'],
  ['createServerLinkRequest(communityId, data)', 'POST /api/v1/admin/{communityId}/server-link-requests', { body: '@data' }],
  ['listCommunityConnections(communityId)', 'GET /api/v1/communities/{communityId}/connections'],
  ['authorizeCommunityConnection(communityId, provider)', 'POST /api/v1/communities/{communityId}/connections/{provider}/authorize'],
  ['disconnectCommunityConnection(communityId, provider)', 'DELETE /api/v1/communities/{communityId}/connections/{provider}'],
];

describe('adminApi request contract', () => {
  for (const row of ADMINAPI_ROWS) {
    it(row[0], () => assertContractRow(adminApi, row, rec.calls));
  }
});
