name: Build twitch

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'trigger/receiver/twitch_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-twitch.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'trigger/receiver/twitch_module/**'
      - 'libs/flask_core/**'
  merge_group:
    types: [checks_requested]
    branches: ['release/**']
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build twitch Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'trigger/receiver/twitch_module'
      module_name: 'twitch'
      module_port: '8010'
    secrets: inherit
