name: Build youtube-live

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'trigger/receiver/youtube_live_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-youtube-live.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'trigger/receiver/youtube_live_module/**'
      - 'libs/flask_core/**'
  merge_group:
    types: [checks_requested]
    branches: ['release/**']
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build youtube-live Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'trigger/receiver/youtube_live_module'
      module_name: 'youtube-live'
      module_port: '8013'
    secrets: inherit
