name: Build inventory-interaction

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'action/interactive/inventory_interaction_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-inventory-interaction.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'action/interactive/inventory_interaction_module/**'
      - 'libs/flask_core/**'
  merge_group:
    types: [checks_requested]
    branches: ['release/**']
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build inventory-interaction Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'action/interactive/inventory_interaction_module'
      module_name: 'inventory-interaction'
      module_port: '8008'
    secrets: inherit
