name: Build workflow-core

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'core/workflow_core_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-workflow-core.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'core/workflow_core_module/**'
      - 'libs/flask_core/**'
  merge_group:
    types: [checks_requested]
    branches: ['release/**']
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build workflow-core Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'core/workflow_core_module'
      module_name: 'workflow-core'
      module_port: '8070'
    secrets: inherit
