name: Build ai-researcher

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'core/ai_researcher_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-ai-researcher.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'core/ai_researcher_module/**'
      - 'libs/flask_core/**'
  merge_group:
    types: [checks_requested]
    branches: ['release/**']
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build ai-researcher Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'core/ai_researcher_module'
      module_name: 'ai-researcher'
      module_port: '8056'
    secrets: inherit
