name: Build hub

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'admin/hub_module/**'
      - '.version'
      - '.github/workflows/build-hub.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'admin/hub_module/**'
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build hub Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'admin/hub_module'
      module_name: 'hub'
      module_port: '8060'
    secrets: inherit
