name: Build discord

on:
  push:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'trigger/receiver/discord_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-discord.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [main, 'v*', 'release/**', 'feature/**', 'fix/**', 'chore/**', 'hotfix/**', 'docs/**', 'refactor/**']
    paths:
      - 'trigger/receiver/discord_module/**'
      - 'libs/flask_core/**'
  merge_group:
    types: [checks_requested]
    branches: ['release/**']
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build discord Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'trigger/receiver/discord_module'
      module_name: 'discord'
      module_port: '8011'
    secrets: inherit
